# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(blank=True, max_length=255, null=True)),
                ('account_email', models.CharField(blank=True, max_length=255, null=True)),
                ('password_email', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_server', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
