# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-18 17:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='pass_email',
            new_name='password_email',
        ),
    ]
