# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20161018_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ambiente',
            old_name='smtp_sever',
            new_name='smtp_server',
        ),
    ]
