# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteempleado',
            name='selloSAT',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facturacliente',
            name='selloSAT',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='facturaproveedor',
            name='selloSAT',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
