# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobanteempleado',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facturaproveedor',
            name='fecha_validacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
