# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_auto_20161013_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='cantidad_encontradas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumen',
            name='cantidad_guardadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resumen',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='resumen',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='cantidad_descargadas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='resumen',
            name='cantidad_validadas',
            field=models.IntegerField(default=0),
        ),
    ]
