# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_auto_20161013_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='dia',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='resumen',
            unique_together=set([('dia', 'tipo')]),
        ),
    ]
