# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0004_auto_20161013_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumen',
            old_name='dia',
            new_name='fecha',
        ),
        migrations.AlterUniqueTogether(
            name='resumen',
            unique_together=set([('fecha', 'tipo')]),
        ),
    ]
