# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_auto_20161013_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='tipo',
            field=models.CharField(choices=[('RECIBIDAS', 'FACTURAS RECIBIDAS'), ('EMITIDAS', 'FACTURAS EMITIDAS')], max_length=9),
        ),
    ]
