# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20161015_1127'),
        ('facturas', '0006_auto_20161013_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresa'),
        ),
    ]
