# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0007_resumen_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumen',
            name='tipo',
            field=models.CharField(choices=[('PROVEEDOR', 'FACTURA DE PROVEEDOR'), ('CLIENTE', 'FACTURA A CLIENTE'), ('EMPLEADO', 'COMPROBANTE DE EMPLEADO')], max_length=9),
        ),
    ]
