# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0008_auto_20161015_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumen',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
