# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-15 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20161015_1127'),
        ('facturas', '0009_resumen_total'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='resumen',
            unique_together=set([('empresa', 'fecha', 'tipo')]),
        ),
    ]
