# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0010_auto_20161015_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumen',
            name='cantidad_descargadas',
        ),
        migrations.RemoveField(
            model_name='resumen',
            name='cantidad_encontradas',
        ),
    ]
