# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20161015_1127'),
        ('facturas', '0014_auto_20161018_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('EXITO', 'EXITO'), ('ERROR', 'ERROR'), ('DETALLE', 'DETALLE'), ('PROCESANDO', 'PROCESANDO')], max_length=10, null=True)),
                ('operacion', models.CharField(choices=[('GET', 'OBTENER'), ('SAVE', 'GUARDAR'), ('VALIDATE', 'VALIDAR')], max_length=8, null=True)),
                ('fecha_operacion', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('ruta', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configuracion.Empresa')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='log',
            unique_together=set([('empresa', 'nombre', 'operacion', 'fecha_operacion')]),
        ),
    ]
