# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0015_auto_20161021_0210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='ruta',
            new_name='url',
        ),
    ]
