# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-21 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0016_auto_20161021_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
